AI_TOPIC_KEYWORDS = {
    "technology": [
        "llm",
        "transformer",
        "diffusion",
        "multimodal",
        "agent",
        "model",
        "neural network",
        "inference",
        "fine-tuning",
        "embedding",
        "rag",
        "vector database",
    ],
    "use_case": [
        "chatbot",
        "copilot",
        "automation",
        "customer support",
        "coding assistant",
        "recommendation",
        "workflow",
        "productivity",
        "analytics",
        "application",
        "deployment",
    ],
    "impact": [
        "impact",
        "adoption",
        "productivity gain",
        "job market",
        "economic",
        "society",
        "education",
        "healthcare",
        "sustainability",
        "future",
        "trend",
    ],
    "research": [
        "paper",
        "benchmark",
        "state of the art",
        "sota",
        "experiment",
        "arxiv",
        "evaluation",
        "dataset",
    ],
    "regulation": [
        "regulation",
        "governance",
        "policy",
        "compliance",
        "ai act",
        "risk management",
    ],
    "ethics": [
        "bias",
        "fairness",
        "transparency",
        "safety",
        "alignment",
        "privacy",
        "responsible ai",
    ],
    "business": [
        "startup",
        "investment",
        "funding",
        "roi",
        "enterprise",
        "strategy",
        "market",
        "revenue",
    ],
}

BLOG_DOMAINS = {
    "medium.com",
    "www.medium.com",
    "substack.com",
    "www.substack.com",
    "dev.to",
    "hashnode.com",
    "www.hashnode.com",
    "blog.google",
    "anthropic.com",
    "www.anthropic.com",
    "openai.com",
    "www.openai.com",
}

NEWS_DOMAINS = {
    "techcrunch.com",
    "www.techcrunch.com",
    "venturebeat.com",
    "www.venturebeat.com",
    "theverge.com",
    "www.theverge.com",
    "wired.com",
    "www.wired.com",
    "reuters.com",
    "www.reuters.com",
    "news.ycombinator.com",
}

RESEARCH_DOMAINS = {
    "arxiv.org",
    "export.arxiv.org",
    "huggingface.co",
    "www.semanticscholar.org",
    "semanticscholar.org",
    "paperswithcode.com",
    "www.paperswithcode.com",
}

JOB_DOMAINS = {
    "linkedin.com",
    "www.linkedin.com",
    "jobs.lever.co",
    "boards.greenhouse.io",
    "wellfound.com",
    "www.wellfound.com",
    "ashbyhq.com",
    "www.ashbyhq.com",
    "remotive.com",
    "www.remotive.com",
    "jobs.ashbyhq.com",
}

NEWS_SIGNAL_KEYWORDS = {
    "announced",
    "breaking",
    "report",
    "reported",
    "press release",
    "news",
    "today",
    "this week",
    "according to",
    "launches",
    "launching",
}

JOB_SIGNAL_TITLE_KEYWORDS = {
    "engineer",
    "scientist",
    "researcher",
    "applied ai",
    "machine learning",
    "ml engineer",
    "ai engineer",
    "llm engineer",
    "genai engineer",
    "hiring",
    "career",
    "job",
}

CONTENT_KIND_KEYWORDS = {
    "news": [
        "news",
        "announced",
        "launch",
        "released",
        "report",
        "update",
        "breaking",
        "press release",
    ],
    "use_case": [
        "use case",
        "case study",
        "implementation",
        "customer story",
        "how we use",
        "workflow",
        "production",
    ],
    "project": [
        "github",
        "repository",
        "open source",
        "framework",
        "library",
        "sdk",
        "tooling",
    ],
    "job_market": [
        "hiring",
        "vacancy",
        "open role",
        "open position",
        "recruiting",
        "job opening",
        "career",
    ],
    "impact": [
        "impact",
        "market demand",
        "adoption",
        "productivity",
        "future direction",
        "trend",
    ],
}

JOB_ROLE_KEYWORDS = [
    "machine learning engineer",
    "ml engineer",
    "ai engineer",
    "llm engineer",
    "genai engineer",
    "agentic ai engineer",
    "data scientist",
    "nlp engineer",
    "research scientist",
    "applied scientist",
    "prompt engineer",
    "ai product manager",
    "mlops engineer",
]

JOB_MARKET_KEYWORDS = [
    "hiring",
    "recruiting",
    "vacancy",
    "open role",
    "open position",
    "job opening",
    "salary",
    "compensation",
    "remote",
    "full-time",
    "part-time",
    "internship",
    "headcount",
]

SOCIAL_DOMAINS = {
    "linkedin.com",
    "www.linkedin.com",
    "x.com",
    "www.x.com",
    "twitter.com",
    "www.twitter.com",
    "reddit.com",
    "www.reddit.com",
}

PREDEFINED_SOURCE_LINKS = {
    "blogs": [
        "https://www.anthropic.com/news",
        "https://www.anthropic.com/engineering",
        "https://medium.com/nlplanet",
        "https://odsc.medium.com",
        "https://medium.com/artificial-corner",
        "https://openai.com/index",
        "https://blog.google/technology/ai/",
    ],
    "github": [
        "https://github.com/topics/artificial-intelligence",
        "https://github.com/topics/llm",
        "https://github.com/topics/ai-agents",
        "https://github.com/topics/machine-learning",
    ],
    "news": [
        "https://www.wsj.com/tech/ai",
        "https://www.wired.com/tag/artificial-intelligence/",
        "https://timesofindia.indiatimes.com/technology",
        "https://www.theverge.com/ai-artificial-intelligence",
    ],
    "research_papers": [
        "https://arxiv.org/list/cs.AI/recent",
        "https://arxiv.org/list/cs.LG/recent",
        "https://arxiv.org/list/cs.CL/recent",
        "https://arxiv.org/list/cs.IR/recent",
    ],
    "job_postings": [
        "https://www.linkedin.com/jobs",
    ],
}
